### ISSUE TITLE
Ability to specify import paths

### ISSUE THREAD

**Issue by rcorre** [bufbuild/buf-language-server#51]
Is there a way to specify the protobuf import paths, similar to the `-I` or `--proto_path` flag to `protoc`? I work in a project where protobuf files are split across separate folders, and the build process joins them together using `--proto_path`. For example, a file might import "Networking.proto", which is located in a different directory. `bufls` shows an error when using goto definition:

```
Blah.proto:8:8:Networking.proto: does not exist
```

**Comment by Rehtt** [comment]
try use `buf.work.yaml` https://buf.build/docs/configuration/v1/buf-work-yaml/#version

**Comment by chrispine** [comment]
Closing this, but feel free to re-open if needed!
